#!/usr/bin/env bash

# https://colors.sh/

s="\033["
e="m"

__COLOR_RESET="${s}0${e}"
__COLOR_RESET_BACKGROUND="${s}${e}"
__COLOR_BOLD="${s}1${e}"
__COLOR_DIM="${s}2${e}"
__COLOR_ITALIC="${s}3${e}"
__COLOR_UNDERLINED="${s}4${e}"
__COLOR_BLINK="${s}5${e}"
__COLOR_YELLOW_LIGHT_BACKGROUND="${s}7${e}"
__COLOR_YELLOW_BLACK_BACKGROUND="${s}30;43${e}"
__COLOR_STRIKETHROUGH="${s}9${e}"
__COLOR_BOLD_OFF="${s}21${e}"
__COLOR_WHITE="${s}39${e}"
__COLOR_GRAY="${s}30${e}"
__COLOR_GRAY_LIGHT="${s}90${e}"
__COLOR_RED="${s}31${e}"
__COLOR_RED_LIGHT="${s}91${e}"
__COLOR_GREEN="${s}32${e}"
__COLOR_GREEN_LIGHT="${s}92${e}"
__COLOR_YELLOW="${s}33${e}"
__COLOR_YELLOW_LIGHT="${s}93${e}"
__COLOR_BLUE="${s}34${e}"
__COLOR_BLUE_LIGHT="${s}94${e}"
__COLOR_MAGENTA="${s}35${e}"
__COLOR_MAGENTA_LIGHT="${s}95${e}"
__COLOR_CYAN="${s}36${e}"
__COLOR_CYAN_LIGHT="${s}96${e}"
